import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:uuid/uuid.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../../viewmodels/notice_viewmodel.dart';
import '../../viewmodels/auth_viewmodel.dart';
import '../../data/models/notice_model.dart';
import '../shared/custom_textfield.dart';
import '../../data/services/gemini_service.dart'; // Native Gemini API framework

class AddNoticeView extends StatefulWidget {
  const AddNoticeView({super.key});

  @override
  State<AddNoticeView> createState() => _AddNoticeViewState();
}

class _AddNoticeViewState extends State<AddNoticeView> {
  final _formKey = GlobalKey<FormState>();
  final _titleCtl = TextEditingController();
  final _descCtl = TextEditingController();
  final _aiPromptCtl = TextEditingController();
  
  String _selectedCategory = 'General';
  bool _isUrgent = false;
  bool _isPinned = false;
  bool _isLoading = false;
  
  bool _isAiPromptMode = false;
  bool _isAiGenerating = false;

  final categories = ['Academic', 'Events', 'Urgent', 'General'];

  Future<void> _generateWithAI() async {
    if (_aiPromptCtl.text.isEmpty) return;
    setState(() { _isAiGenerating = true; });
    
    _titleCtl.clear();
    _descCtl.clear();
    
    try {
      final aiResult = await GeminiService.generateNoticeFromPrompt(_aiPromptCtl.text);
      String finalTitle = aiResult['title']!;
      String finalDesc = aiResult['body']!;
      
      // Preserve the majestic UI typing effect, but feed it real AI context!
      for (int i = 0; i < finalTitle.length; i++) {
          if (!mounted) return;
          _titleCtl.text += finalTitle[i];
          await Future.delayed(const Duration(milliseconds: 20));
      }
      
      for (int i = 0; i < finalDesc.length; i++) {
          if (!mounted) return;
          _descCtl.text += finalDesc[i];
          await Future.delayed(const Duration(milliseconds: 10));
      }

      if (!mounted) return;
      setState(() { _isUrgent = false; });
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Notice generated by Gemini AI ⚡')));
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content: Text(e.toString().replaceAll('Exception: ', '')), 
        backgroundColor: Colors.redAccent,
        duration: const Duration(seconds: 4),
      ));
    } finally {
      if (mounted) setState(() { _isAiGenerating = false; _isAiPromptMode = false; });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(title: const Text('Create Event', style: TextStyle(color: Colors.white)), backgroundColor: Colors.transparent, iconTheme: const IconThemeData(color: Colors.white)),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              if (!_isAiPromptMode && !_isAiGenerating)
                Container(
                  margin: const EdgeInsets.only(bottom: 32),
                  child: OutlinedButton.icon(
                    style: OutlinedButton.styleFrom(
                      foregroundColor: const Color(0xFFA78BFA),
                      padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                      side: const BorderSide(color: Color(0xFF4C1D95)),
                      backgroundColor: const Color(0xFF2E1065).withOpacity(0.5),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16))
                    ),
                    onPressed: () => setState(() => _isAiPromptMode = true),
                    icon: const Icon(Icons.auto_awesome),
                    label: const Text('Draft with Gemini AI ⚡', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
                  ),
                ).animate().shimmer(duration: 2.seconds, color: Colors.white24),
                
              if (_isAiPromptMode)
                Container(
                  margin: const EdgeInsets.only(bottom: 32),
                  padding: const EdgeInsets.all(24),
                  decoration: BoxDecoration(
                    color: const Color(0xFF111827),
                    borderRadius: BorderRadius.circular(16),
                    border: Border.all(color: const Color(0xFF374151)),
                    boxShadow: [BoxShadow(color: Colors.black.withOpacity(0.5), blurRadius: 10)]
                  ),
                  child: Column(
                    children: [
                      Row(
                        children: [
                          const Icon(Icons.auto_awesome, color: Color(0xFFA78BFA)),
                          const SizedBox(width: 8),
                          const Text('AI Generation Prompt', style: TextStyle(color: Color(0xFFC4B5FD), fontWeight: FontWeight.bold, fontSize: 16)),
                          const Spacer(),
                          IconButton(icon: const Icon(Icons.close, color: Color(0xFF9CA3AF)), onPressed: () => setState(() => _isAiPromptMode = false))
                        ],
                      ),
                      const SizedBox(height: 16),
                      TextField(
                        controller: _aiPromptCtl,
                        style: const TextStyle(color: Colors.white),
                        decoration: InputDecoration(
                          hintText: 'e.g. "Meeting next Friday at 4pm"',
                          hintStyle: const TextStyle(color: Color(0xFF6B7280)),
                          filled: true,
                          fillColor: const Color(0xFF1F2937),
                          border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Color(0xFF374151))),
                        ),
                      ),
                      const SizedBox(height: 16),
                      SizedBox(
                        width: double.infinity,
                        child: FilledButton(
                          style: FilledButton.styleFrom(backgroundColor: const Color(0xFF8B5CF6)),
                          onPressed: _isAiGenerating ? null : _generateWithAI,
                          child: _isAiGenerating ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2)) : const Text('Generate Options ⚡', style: TextStyle(color: Colors.white)),
                        ),
                      )
                    ],
                  ),
                ).animate().fadeIn().slideY(begin: -0.05),
            
              CustomTextField(
                controller: _titleCtl,
                label: 'Notice Title',
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<String>(
                value: _selectedCategory,
                dropdownColor: const Color(0xFF1F2937),
                decoration: InputDecoration(
                  labelText: 'Category',
                  filled: true,
                  fillColor: const Color(0xFF1F2937),
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Color(0xFF374151))),
                  enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(12), borderSide: const BorderSide(color: Color(0xFF374151))),
                  labelStyle: const TextStyle(color: Color(0xFF9CA3AF))
                ),
                items: categories.map((cat) {
                  return DropdownMenuItem(value: cat, child: Text(cat, style: const TextStyle(color: Colors.white)));
                }).toList(),
                onChanged: (val) => setState(() => _selectedCategory = val!),
              ),
              const SizedBox(height: 24),
              CustomTextField(
                controller: _descCtl,
                label: 'Event Details',
                maxLines: 8,
                validator: (val) => val == null || val.isEmpty ? 'Required' : null,
              ),
              const SizedBox(height: 24),
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: const Color(0xFF111827),
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: const Color(0xFF374151))
                ),
                child: Column(
                  children: [
                    SwitchListTile(
                      title: const Text('High Priority Override', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
                      subtitle: const Text('Forces red marquee and kiosk bypass', style: TextStyle(color: Color(0xFF9CA3AF))),
                      activeColor: Colors.white,
                      activeTrackColor: const Color(0xFFEF4444),
                      value: _isUrgent,
                      onChanged: (v) => setState(() => _isUrgent = v),
                    ),
                    const Divider(height: 1, color: Color(0xFF374151)),
                    SwitchListTile(
                      title: const Text('Pin to Master Feed', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold)),
                      subtitle: const Text('Stays anchored above chronological events', style: TextStyle(color: Color(0xFF9CA3AF))),
                      activeColor: Colors.white,
                      activeTrackColor: const Color(0xFFF59E0B),
                      value: _isPinned,
                      onChanged: (v) => setState(() => _isPinned = v),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 48),
              if (_isLoading)
                const Center(child: CircularProgressIndicator())
              else
                FilledButton.icon(
                  onPressed: () async {
                    if (_formKey.currentState!.validate()) {
                      setState(() => _isLoading = true);
                      try {
                        final authUser = context.read<AuthViewModel>().authUser;
                        final newNotice = Notice(
                          id: const Uuid().v4(),
                          title: _titleCtl.text.trim(),
                          description: _descCtl.text.trim(),
                          category: _selectedCategory,
                          createdAt: DateTime.now(),
                          authorId: authUser?.uid ?? '',
                          isUrgent: _isUrgent,
                          isPinned: _isPinned,
                        );
                        await context.read<NoticeViewModel>().addNotice(newNotice);
                        if (mounted) Navigator.pop(context);
                      } catch (e) {
                         ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
                      } finally {
                        if (mounted) setState(() => _isLoading = false);
                      }
                    }
                  },
                  icon: const Icon(Icons.send, color: Colors.white),
                  label: const Text('Publish Smart Notice', style: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),
                  style: FilledButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 20)),
                )
            ],
          ),
        ),
      ),
    );
  }
}
