// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGoSNPcC7QfBQFqmv1YRCbrw2g0TQ0U1I',
    appId: '1:505781818613:web:07d80caa07cb0f086361bc',
    messagingSenderId: '505781818613',
    projectId: 'digitalnoticeboard-fb73c',
    authDomain: 'digitalnoticeboard-fb73c.firebaseapp.com',
    storageBucket: 'digitalnoticeboard-fb73c.firebasestorage.app',
    measurementId: 'G-67D0J4G1YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi2kdKXhp1TWol9Cjck6w-QC9xaF3i8x8',
    appId: '1:505781818613:android:d5d30c53482a65b36361bc',
    messagingSenderId: '505781818613',
    projectId: 'digitalnoticeboard-fb73c',
    storageBucket: 'digitalnoticeboard-fb73c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHn45Tm60zj5P2ZRl0xkRPMGSRTTrOM-0',
    appId: '1:505781818613:ios:e2ee4c49b2b9d27b6361bc',
    messagingSenderId: '505781818613',
    projectId: 'digitalnoticeboard-fb73c',
    storageBucket: 'digitalnoticeboard-fb73c.firebasestorage.app',
    iosBundleId: 'com.example.digitalNoticeBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHn45Tm60zj5P2ZRl0xkRPMGSRTTrOM-0',
    appId: '1:505781818613:ios:e2ee4c49b2b9d27b6361bc',
    messagingSenderId: '505781818613',
    projectId: 'digitalnoticeboard-fb73c',
    storageBucket: 'digitalnoticeboard-fb73c.firebasestorage.app',
    iosBundleId: 'com.example.digitalNoticeBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGoSNPcC7QfBQFqmv1YRCbrw2g0TQ0U1I',
    appId: '1:505781818613:web:29ffb3c476be65d96361bc',
    messagingSenderId: '505781818613',
    projectId: 'digitalnoticeboard-fb73c',
    authDomain: 'digitalnoticeboard-fb73c.firebaseapp.com',
    storageBucket: 'digitalnoticeboard-fb73c.firebasestorage.app',
    measurementId: 'G-9BZHGE0EXY',
  );

}